linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - exportloopref
    - exhaustive
    - goconst
    - gofmt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - rowserrcheck
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - asciicheck
    - godot
#    - stylecheck
    - gocyclo
    - gocritic
    - errcheck
    - thelper
    - tparallel
    - wastedassign
    - predeclared
    - nilerr
    - makezero
    - forbidigo
    - errname
    - nilnil
    - tenv
    - depguard
    - gci
  # Fails with go 1.18 until https://github.com/golangci/golangci-lint/issues/2649 is resolved
  #    - nolintlint

  # don't enable:
  # - ireturn
  # - gocognit
  # - gochecknoglobals
  # - goerr113
  # - interfacer
  # - maligned
  # - nestif
  # - prealloc
  # - revive
  # - wsl
  # - testpackage
  # - depguard
  # - dogsled
  # - dupl
  # - errcheck
  # - funlen
  # - golint
  # - gomnd
  # - lll
  # - varnamelen

linters-settings:
  golint:
    min-confidence: 0
  depguard:
    list-type: denylist
    packages:
      - github.com/pkg/errors
  gci:
    sections:
      - Standard
      - Default
      - "Prefix(github.com/FriendsOfShopware/shopware-cli)"

issues:
  exclude-rules:
    - path: cmd\/*
      linters:
        - forbidigo

run:
  skip-dirs:
    - version
