linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - exportloopref
    - exhaustive
    - goconst
    - gofmt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - asciicheck
    - godot
    - gocyclo
    - gocritic
    - errcheck
    - thelper
    - tparallel
    - predeclared
    - nilerr
    - makezero
    - forbidigo
    - errname
    - nilnil
    - tenv
    - depguard
    - gofumpt
    - bidichk
    - containedctx
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errname
    - ginkgolinter
    - gocheckcompilerdirectives
    - goconst
    - godot
    - godox
    - nilnil

linters-settings:
  golint:
    min-confidence: 0
  gci:
    sections:
      - Standard
      - Default
      - "Prefix(github.com/FriendsOfShopware/shopware-cli)"

issues:
  exclude-rules:
    - path: cmd\/*
      linters:
        - forbidigo

run:
  skip-dirs:
    - version
