before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./scripts/completion.sh

builds:
  - env:
      - CGO_ENABLED=0
    binary: shopware-cli
    ldflags: -s -w -X 'github.com/FriendsOfShopware/shopware-cli/cmd.version={{ .Version }}'
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: linux
        goarch: '386'
      - goos: windows
        goarch: '386'
      - goos: windows
        goarch: 'arm64'

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    rlcp: true
    files:
      - LICENSE
      - completions/*

release:
  github:
    owner: FriendsOfShopware
    name: shopware-cli

dockers:
  # AMD64
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2-amd64"
      - "friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2-amd64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.2"
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-8.1-amd64"
      - "friendsofshopware/shopware-cli:{{ .Tag }}-php-8.1-amd64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.1"
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-7.4-amd64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=7.4"
      - "--platform=linux/amd64"
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-7.2-amd64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=7.2"
      - "--platform=linux/amd64"

  # ARM64
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2-arm64"
      - "friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2-arm64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.2"
      - "--platform=linux/arm64"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-8.1-arm64"
      - "friendsofshopware/shopware-cli:{{ .Tag }}-php-8.1-arm64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=8.1"
      - "--platform=linux/arm64"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-7.4-arm64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=7.4"
      - "--platform=linux/arm64"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-7.2-arm64"
    build_flag_templates:
      - "--build-arg=PHP_VERSION=7.2"
      - "--platform=linux/arm64"

docker_manifests:
  # GHCR
  - name_template: ghcr.io/friendsofshopware/shopware-cli:latest
    image_templates:
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2-amd64"
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2-arm64"

  - name_template: ghcr.io/friendsofshopware/shopware-cli:latest-php-8.2
    image_templates:
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2-amd64"
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2-arm64"

  - name_template: ghcr.io/friendsofshopware/shopware-cli:latest-php-8.1
    image_templates:
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-8.1-amd64"
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-8.1-arm64"

  - name_template: ghcr.io/friendsofshopware/shopware-cli:latest-php-7.4
    image_templates:
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-7.4-amd64"
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-7.4-arm64"

  - name_template: ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}
    image_templates:
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2-amd64"
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2-arm64"

  - name_template: ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2
    image_templates:
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2-amd64"
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2-arm64"

  - name_template: ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-8.1
    image_templates:
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-8.1-amd64"
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-8.1-arm64"

  - name_template: ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-7.4
    image_templates:
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-7.4-amd64"
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-7.4-arm64"
    
  - name_template: ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-7.2
    image_templates:
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-7.2-amd64"
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}-php-7.2-arm64"

  # Docker Hub
  - name_template: friendsofshopware/shopware-cli:latest
    image_templates:
      - "friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2-amd64"
      - "friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2-arm64"

  - name_template: friendsofshopware/shopware-cli:latest-php-8.2
    image_templates:
      - "friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2-amd64"
      - "friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2-arm64"

  - name_template: friendsofshopware/shopware-cli:latest-php-8.1
    image_templates:
      - "friendsofshopware/shopware-cli:{{ .Tag }}-php-8.1-amd64"
      - "friendsofshopware/shopware-cli:{{ .Tag }}-php-8.1-arm64"

  - name_template: friendsofshopware/shopware-cli:{{ .Tag }}
    image_templates:
      - "friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2-amd64"
      - "friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2-arm64"

  - name_template: friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2
    image_templates:
      - "friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2-amd64"
      - "friendsofshopware/shopware-cli:{{ .Tag }}-php-8.2-arm64"

  - name_template: friendsofshopware/shopware-cli:{{ .Tag }}-php-8.1
    image_templates:
      - "friendsofshopware/shopware-cli:{{ .Tag }}-php-8.1-amd64"
      - "friendsofshopware/shopware-cli:{{ .Tag }}-php-8.1-arm64"

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    env:
      - COSIGN_EXPERIMENTAL=1
    artifacts: checksum
    args:
    - "sign-blob"
    - "--output-certificate=${certificate}"
    - "--output-signature=${signature}"
    - '${artifact}'
    - "--yes"

docker_signs:
  - cmd: cosign
    env:
    - COSIGN_EXPERIMENTAL=1
    artifacts: all
    args:
    - 'sign'
    - '${artifact}'
    - "--yes"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request:'

aurs:
  - homepage: https://sw-cli.fos.gg
    description: A cli which contains handy helpful commands for daily Shopware tasks
    license: MIT
    maintainers:
      - "Soner Sayakci <hi@shyim.de>"
      - "Max <max@swk-web.com>"
    private_key: '{{ .Env.AUR_KEY }}'
    commit_author:
      name: Frosh Automation
      email: ci@fos.gg
    git_url: 'ssh://aur@aur.archlinux.org/shopware-cli-bin.git'
    depends:
      - "git"
    package: |-
      install -Dm755 "./shopware-cli" "${pkgdir}/usr/bin/shopware-cli"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/shopware-cli/LICENSE"

      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/shopware-cli.bash" "${pkgdir}/usr/share/bash-completion/completions/shopware-cli"
      install -Dm644 "./completions/shopware-cli.zsh" "${pkgdir}/usr/share/zsh/site-functions/_shopware-cli"
      install -Dm644 "./completions/shopware-cli.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/shopware-cli.fish"

nfpms:
  -
    package_name: shopware-cli
    vendor: FriendsOfShopware
    homepage: https://github.com/FriendsOfShopware/shopware-cli/
    maintainer: Shyim <github@shyim.de>
    description: A cli which contains handy helpful commands for daily Shopware tasks
    license: MIT
    contents:
      - src: ./completions/shopware-cli.bash
        dst: /etc/bash_completion.d/shopware-cli
      - src: ./completions/shopware-cli.fish
        dst: /usr/share/fish/completions/shopware-cli.fish
      - src: ./completions/shopware-cli.zsh
        dst: /usr/local/share/zsh/site-functions/_shopware-cli
    formats:
      - apk
      - deb
      - rpm

brews:
  - tap:
      owner: FriendsOfShopware
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Frosh Automation
      email: ci@fos.gg
    folder: Formula
    goarm: "7"
    homepage: https://friendsofshopware.com
    description: Shopware CLI helps Shopware developers manage extensions
    license: MIT
    test: |
      system "#{bin}/shopware-cli --version"
    dependencies:
    - name: node-sass
    - name: git
      type: optional
    - name: node
      type: optional
    install: |-
      bin.install "shopware-cli"
      bash_completion.install "completions/shopware-cli.bash" => "_shopware-cli"
      zsh_completion.install "completions/shopware-cli.zsh" => "_shopware-cli"
      fish_completion.install "completions/shopware-cli.fish"
