before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./scripts/completion.sh

builds:
  - env:
      - CGO_ENABLED=0
    binary: shopware-cli
    ldflags: -s -w -X 'github.com/FriendsOfShopware/shopware-cli/cmd.version={{ .Version }}'
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: linux
        goarch: '386'
      - goos: windows
        goarch: '386'
      - goos: windows
        goarch: 'arm64'

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - completions/*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: FriendsOfShopware
    name: shopware-cli

dockers:
  - image_templates:
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}"
      - "ghcr.io/friendsofshopware/shopware-cli:v{{ .Major }}"
      - "ghcr.io/friendsofshopware/shopware-cli:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/friendsofshopware/shopware-cli:latest"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  -
    package_name: shopware-cli
    vendor: FriendsOfShopware
    homepage: https://github.com/FriendsOfShopware/shopware-cli/
    maintainer: Shyim <github@shyim.de>
    description: A Shopware CLI
    license: MIT
    contents:
      - src: ./completions/shopware-cli.bash
        dst: /etc/bash_completion.d/shopware-cli
      - src: ./completions/shopware-cli.fish
        dst: /usr/share/fish/completions/shopware-cli.fish
      - src: ./completions/shopware-cli.zsh
        dst: /usr/local/share/zsh/site-functions/_shopware-cli
    formats:
      - apk
      - deb
      - rpm

brews:
  - tap:
      owner: FriendsOfShopware
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Soner Sayakci
      email: s.sayakci@shopware.com
    folder: Formula
    goarm: "7"
    homepage: https://friendsofshopware.com
    description: Shopware CLI helps Shopware developers manage extensions
    license: MIT
    test: |
      system "#{bin}/shopware-cli --version"
    dependencies:
    - name: git
      type: optional
    - name: node
      type: optional
    install: |-
      bin.install "shopware-cli"
      bash_completion.install "completions/shopware-cli.bash" => "_shopware-cli"
      zsh_completion.install "completions/shopware-cli.zsh" => "_shopware-cli"
      fish_completion.install "completions/shopware-cli.fish"
