name: Update Base Docker Image
on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile.base'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Image
        run: docker build -t ghcr.io/friendsofshopware/shopware-cli-base:7.4 -f Dockerfile.base  .

      - name: Push Image
        run: docker push ghcr.io/friendsofshopware/shopware-cli-base:7.4