name: Update Base Docker Image
on:
  workflow_dispatch:
  push:
    tags-ignore:
      - "*"
    paths:
      - 'Dockerfile.base'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["8.1", "7.4", "7.2"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Image
        run: docker build -t ghcr.io/friendsofshopware/shopware-cli-base:phpv${{ matrix.php-version }} -f Dockerfile.base --build-arg="PHP_VERSION=${{ matrix.php-version }}" .

      - name: Push Image
        run: docker push ghcr.io/friendsofshopware/shopware-cli-base:phpv${{ matrix.php-version }}
