name: Codespaces

on:
    push:
        branches:
            - main
        paths:
            - .devcontainer/Dockerfile

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Login into Github Docker Registry
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .devcontainer
                push: true
                platforms: linux/amd64,linux/arm64
                tags: "ghcr.io/friendsofshopware/shopware-cli-codespace"
                provenance: false
