name: Update docs content

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'extension/shopware-extension-schema.json'
      - 'shopware-project-schema.json'

jobs:
  config-schema-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create config.schema.md
        run: |
          npm install wetzel -g
          wetzel extension/shopware-extension-schema.json >> schema.new.md
          wetzel shop/shopware-project-schema.json >> project.new.md

      - name: Commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          echo -e "---\n title: 'Schema of .shopware-extension.yml' \n---\n\n$(cat schema.new.md)" > schema.new.md
          echo -e "---\n title: 'Schema of .shopware-project.yml' \n---\n\n$(cat project.new.md)" > project.new.md
          rm -rf wiki/docs/shopware-extensions.yml-schema/index.md
          rm -ff wiki/docs/shopware-project.yml-schema/index.md
          mv schema.new.md wiki/docs/shopware-extensions.yml-schema/index.md
          mkdir -p wiki/docs/shopware-project.yml-schema/ || true
          mv project.new.md wiki/docs/shopware-project.yml-schema/index.md
          git add -f wiki/docs/shopware-extensions.yml-schema/index.md wiki/docs/shopware-project.yml-schema/index.md
          git commit -m "chore: Update json schema docs"
          git push
