name: Tests

on:
  push:
    branches: [ "main" ]
    tags-ignore:
      - "*"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.os }}
    env:
      SHOPWARE_CLI_DISABLE_WASM_CACHE: 1
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-14
          - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        check-latest: true
        cache: true

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
