name: Run tests

on:
  push:
    branches: [ "main" ]
    tags-ignore:
      - "*"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"
        cache: true

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
