name: Nix Update
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "go.sum"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for Updates
        run: nix run github:Mic92/nix-update -- shopware-cli --url https://github.com/FriendsOfShopware/shopware-cli --flake

      - name: Commit file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          if [[ `git status --porcelain` ]]; then
            git commit -m "chore: Update vendor sha"
            git push
          fi
