name: Nix Update
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "go.sum"

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache: true

      - name: Check for Updates
        run: go run .github/nix-update.go

      - uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: Frosh Automation
          author_email: ci@fos.gg
          message: "chore: Update vendor sha"
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
