name: Nix Update
on:
  workflow_dispatch:
  push:
    paths:
      - "go.sum"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for Updates
        run: nix run github:Mic92/nix-update -- composer-registry --url https://github.com/FriendsOfShopware/shopware-cli --flake

      - name: Commit file
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: Update vendor sha"
