name: Nix Update
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "go.sum"

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for Updates
        run: nix run github:Mic92/nix-update -- shopware-cli --url https://github.com/FriendsOfShopware/shopware-cli --flake

      - uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: Frosh Automation
          author_email: ci@fos.gg
          message: "chore: Update vendor sha"
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
